version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://prerna_db_user:7LGdbfizwfMioJ1G@cluster0.dgfcpdx.mongodb.net/?appName=Cluster0
    networks:
      - app_network
    restart: always

  frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "3000:3000"
    environment:
      - FLASK_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
